name: 'Setup Testing Environment'
description: 'Set up the testing environment for running tests from the build workflow.'

inputs:
  package:
    description: 'The package to set up the test environment for.'
    required: true
    default: 'all'

runs:
  using: 'composite'
  steps:
    - name: Setup Test Environment
      shell: bash
      run: |
        cd apps/playground-ui
        cp .env.example .env
