name: Publish UI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - dev
          - prod

permissions:
  contents: read
  pull-requests: write
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Only allow main branch to deploy to production and next branch to deploy to development
    if: (github.ref == 'refs/heads/main' && github.event.inputs.environment == 'prod') || (github.ref == 'refs/heads/next' && github.event.inputs.environment == 'dev')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        id: deploy
        run: |
          DEPLOYMENT_URL=$(vercel deploy \
          --token ${{ secrets.VERCEL_TOKEN }} \
          --project ${{ secrets.VERCEL_PROJECT_ID_PLAYGROUND }} \
          --scope ${{ secrets.VERCEL_SCOPE }} \
          --target ${{ github.event.inputs.environment == 'prod' && 'production' || 'development' }} \
          --force \
          --cwd apps/playground-ui)
          echo "deployment-url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT

      - name: Set Alias
        run: |
          vercel alias set \
          ${{ steps.deploy.outputs.deployment-url }} \
          ${{ github.event.inputs.environment == 'prod' && secrets.DOMAIN_PLAYGROUND_PROD || secrets.DOMAIN_PLAYGROUND_DEV }} \
          --token ${{ secrets.VERCEL_TOKEN }} \
          --scope ${{ secrets.VERCEL_SCOPE }}
